### ISSUE TITLE
Binary missing since version v1.0.1

### ISSUE THREAD

**Issue by roukmoute** [kubernetes-sigs/mdtoc#19]
I've noticed that since version v1.0.1, the binary file is no longer available for download. 

However, [the documentation suggests](https://github.com/kubernetes-sigs/mdtoc?tab=readme-ov-file#installation) that you only need to download this binary to use the software. 

Would it be possible to make this file available again? Manual compilation can be quite tedious, and I think the availability of the binary would make installation much easier for many users.

Thanks in advance

**Comment by saschagrunert** [comment]
@roukmoute thank you for the request. We could manually upload the binaries for the releases for now, but in the long term we need something automated like we have in [other tools](https://github.com/kubernetes-sigs/zeitgeist/blob/master/.github/workflows/release.yml).

cc @cpanato if you're interested in picking this up.

**Comment by cpanato** [comment]
will take it

/assign

**Comment by cpanato** [comment]
you can download the binary from the new release: https://github.com/kubernetes-sigs/mdtoc/releases/tag/v1.2.0
